# Generated by Django 2.1.2 on 2018-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('place', models.TextField()),
                ('thing', models.TextField()),
                ('thought', models.TextField()),
            ],
        ),
    ]
