# Generated by Django 2.1.2 on 2018-11-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.TextField()),
                ('UserPW', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.TextField(),
        ),
    ]
